#!/bin/sh

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
BOLD='\033[1m' # Bold
NORMAL='\033[0m' # Normal

SCRIPT_DIR="$(dirname "$0")"
BASE_URL='https://activity-service.prod.careem-rh.com'
LIMIT=10

RAW_MODE=0

while getopts "rn:h" opt; do
  case $opt in
    n)
      LIMIT="$OPTARG"
      ;;
    r)
      RAW_MODE=1
      ;;
    h)
      echo "Usage: $0 [-n limit:10] [-r] userid1 ..."
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

function print_activities {
  local USERID=$1
  local limit=$2

  echo ""
  echo "Activity_History_of_User[$limit]: ${GREEN}${BOLD}${USERID}${NC}"
  echo ""

  local has_next='true'
  local next_cursor=

  while (( limit > 0 )) && [ "$has_next" == 'true' ]; do

    local URL="${BASE_URL}/v2/user/${USERID}/activities?activity_type=ride&next_cursor=$next_cursor"

    local json_data=$(curl -s ${URL})

    if [ $RAW_MODE -eq 1 ]; then
      echo "$json_data" | jq --arg limit $limit -r ".activities[0:$limit]"
    else
      echo "$json_data" | jq --arg limit $limit -rf $SCRIPT_DIR/filter.jq
    fi


    count=$(echo "$json_data" | jq --arg limit $limit -r ".activities[0:$limit] | length")

    ((limit -= count))

    next_cursor=$(echo "$json_data" | jq -r '.paging.next_cursor')
    has_next=$(echo "$json_data" | jq -r '.paging.has_next // false')

  done
}


if [ -p /dev/stdin ]; then
  while IFS= read -r USERID; do
    print_activities $USERID $LIMIT
  done
else
  for (( i=1; i<=$#; i++ ))
  do
    eval arg=\${$i}
    USERID="$arg"
    print_activities $USERID $LIMIT
  done
fi

