#!/bin/bash

if [ "${AUTH_HEADER_SOLUTIONS}" = "" ]; then
  echo "Empty Auth. Please do 'export AUTH_HEADER_SOLUTIONS='<value-here>'"
  exit 1
fi

for (( i=1; i<=$#; i++ ))
do

  eval arg=\${$i}
  searchKey="$arg"

  curl --no-progress-meter 'https://solutions.careempartner.com/user/quickSearch' \
    -H 'accept: */*' \
    -H 'accept-language: en-US,en;q=0.9' \
    -H 'content-type: application/json' \
    -b "${AUTH_HEADER_SOLUTIONS}" \
    --data-raw "{\"serviceProviderId\":1,\"searchKey\":\"${searchKey}\",\"start\":0}" \
    | jq -r -f ~/bin/filter-solutions.jq

done
